export const ErrorCode = {
  BAD_REQUEST: 'BAD_REQUEST',
  LOG_CREATE_FAILED: 'LOG_CREATE_FAILED',
  STATISTICS_CREATE_FAILED: 'STATISTICS_CREATE_FAILED',
  STATISTICS_COUNT_RESET_FAILED: 'STATISTICS_COUNT_RESET_FAILED',
  CREATE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
